[project]
name = "multijsnake"
version = "0.1.0"
description = "MultiJSnake project dependencies"
requires-python = ">=3.11,<=3.12"
dependencies = [
    "tensorflow==2.20.0",
    "keras==3.13.2",
    "JPype1==1.5.0",
]

[project.optional-dependencies]
visualization = [
    "pygame==2.6.0"
]